import { Product, Category, VisitorStats } from './types';

export const CATEGORIES: Category[] = [
  { id: '1', name: 'Thời Trang Nam', iconName: 'Shirt' },
  { id: '7', name: 'Thời Trang Nữ', iconName: 'ShoppingBag' },
  { id: '2', name: 'Mỹ Phẩm', iconName: 'Sparkles' },
  { id: '3', name: 'Đồ Điện Tử', iconName: 'Smartphone' },
  { id: '4', name: 'Đồ Gia Dụng', iconName: 'Home' },
  { id: '5', name: 'Sức Khoẻ', iconName: 'HeartPulse' },
  { id: '6', name: 'Mẹ & Bé', iconName: 'Baby' },
];

export const MOCK_PRODUCTS: Product[] = [
  {
    id: 'p1',
    title: 'Áo Thun Nam Cổ Tròn Unisex Cotton Form Rộng Phong Cách Hàn Quốc',
    price: 45000,
    originalPrice: 150000,
    discountPercent: 70,
    image: 'https://images.unsplash.com/photo-1521572163474-6864f9cf17ab?auto=format&fit=crop&q=80&w=400',
    categoryId: '1',
    affiliateLink: 'https://shopee.vn',
    platform: 'shopee',
    soldCount: 15420,
    description: 'Áo thun form rộng thoải mái, chất liệu cotton 100% thấm hút mồ hôi tốt. Phù hợp cho cả nam và nữ năng động.',
    isSuggested: true,
  },
  {
    id: 'p2',
    title: 'Kem Dưỡng Da Mặt Sáng Mịn Chống Lão Hoá Ban Đêm 50ml',
    price: 250000,
    originalPrice: 400000,
    discountPercent: 38,
    image: 'https://images.unsplash.com/photo-1620916566398-39f1143ab7be?auto=format&fit=crop&q=80&w=400',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    categoryId: '2',
    affiliateLink: 'https://tiktok.com',
    platform: 'tiktok',
    soldCount: 8930,
    description: 'Kem dưỡng ẩm chuyên sâu giúp phục hồi làn da trong lúc ngủ. Cung cấp collagen tự nhiên.',
    isSuggested: true,
  },
  {
    id: 'p3',
    title: 'Tai Nghe Bluetooth Không Dây 5.3 Chống Ồn Chủ Động Chơi Game Chuyên Nghiệp',
    price: 199000,
    originalPrice: 450000,
    discountPercent: 55,
    image: 'https://images.unsplash.com/photo-1590658268037-6bf12165a8df?auto=format&fit=crop&q=80&w=400',
    categoryId: '3',
    affiliateLink: 'https://shopee.vn',
    platform: 'shopee',
    soldCount: 23100,
    description: 'Kết nối ổn định, âm bass mạnh mẽ, pin trâu đến 24 giờ. Tích hợp mic đàm thoại rõ nét.',
    isSuggested: false,
  },
  {
    id: 'p4',
    title: 'Nồi Chiên Không Dầu Điện Tử Thông Minh Cỡ Lớn 8 Lít Đa Năng',
    price: 1150000,
    originalPrice: 2000000,
    discountPercent: 42,
    image: 'https://images.unsplash.com/photo-1626806787426-5910811b6325?auto=format&fit=crop&q=80&w=400',
    categoryId: '4',
    affiliateLink: 'https://lazada.vn',
    platform: 'lazada',
    soldCount: 4500,
    description: 'Nấu ăn không cần dầu mỡ, bảo vệ sức khỏe gia đình. Bảng điều khiển cảm ứng dễ sử dụng.',
    isSuggested: false,
  },
  {
    id: 'p5',
    title: 'Son Môi Lì Dưỡng Ẩm Chống Trôi Màu Sắc Tự Nhiên Dành Cho Phái Đẹp',
    price: 99000,
    originalPrice: 250000,
    discountPercent: 60,
    image: 'https://images.unsplash.com/photo-1586495777744-4413f21062fa?auto=format&fit=crop&q=80&w=400',
    videoUrl: 'https://www.w3schools.com/html/mov_bbb.mp4',
    categoryId: '2',
    affiliateLink: 'https://tiktok.com',
    platform: 'tiktok',
    soldCount: 18450,
    description: 'Lên màu chuẩn, giữ ẩm tốt không gây khô môi. Thiết kế sang trọng.',
    isSuggested: true,
  },
  {
    id: 'p6',
    title: 'Đồng Hồ Nam Nữ Kiểu Dáng Thể Thao Chống Nước Dây Cao Su',
    price: 150000,
    originalPrice: 300000,
    discountPercent: 50,
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&q=80&w=400',
    categoryId: '1',
    affiliateLink: 'https://shopee.vn',
    platform: 'shopee',
    soldCount: 6720,
    description: 'Phong cách năng động, chống thấm nước mức độ 3ATM. Mặt kính chống xước.',
    isSuggested: false,
  },
  {
    id: 'p7',
    title: 'Váy Nữ Trễ Vai Voan Tơ Hoạ Tiết Hoa Nhí Thiết Kế Dáng Xoè Cực Xinh',
    price: 175000,
    originalPrice: 320000,
    discountPercent: 45,
    image: 'https://images.unsplash.com/photo-1595777457583-95e059d581b8?auto=format&fit=crop&q=80&w=400',
    categoryId: '7',
    affiliateLink: 'https://shopee.vn',
    platform: 'shopee',
    soldCount: 5210,
    description: 'Váy voan tơ tằm cao cấp, hai lớp dày dặn đứng form. Đi chơi, đi tiệc đều rất duyên dáng, nữ tính.',
    isSuggested: true,
  }
];

export const MOCK_STATS: VisitorStats = {
  totalVisitors: 0,
  activeUsers: 0,
  conversionRate: 0,
  popularCategory: 'Chưa có',
};
